[package]
name = "hap"
version = "0.0.1"
authors = ["Elias Wilken <eliasw@me.com>"]
description = "Rust implementation of the Apple HomeKit Accessory Protocol (HAP)"
homepage = "https://github.com/ewilken/hap-rs"
repository = "https://github.com/ewilken/hap-rs"
readme = "README.md"
license = "MIT"

[dependencies]
eui48 = "0.3.0"
rand = "0.4"
uuid = { version = "0.5.1", features = ["v4"] }
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
byteorder = "1.2.1"
rust-crypto = "0.2.36"
iron = "0.6.0"
router = "0.6.0"
mdns = { git = "https://github.com/plietar/rust-mdns" }
srp = "0.2.4"
sha2 = "0.6.0"
pnet = "0.20.0"
log = "0.4.1"
