[package]
name = "hap"
version = "0.0.1"
authors = ["Elias Wilken <eliasw@me.com>"]
description = "Rust implementation of the Apple HomeKit Accessory Protocol (HAP)"
homepage = "https://github.com/ewilken/hap-rs"
repository = "https://github.com/ewilken/hap-rs"
readme = "README.md"
license = "MIT"

[dependencies]
hwaddr = "0.1.3"
mdns = { git = "https://github.com/plietar/rust-mdns" }
