[package]
name = "hap"
version = "0.0.1"
authors = ["Elias Wilken <eliasw@me.com>"]
description = "Rust implementation of the Apple HomeKit Accessory Protocol (HAP)"
homepage = "https://github.com/ewilken/hap-rs"
repository = "https://github.com/ewilken/hap-rs"
readme = "README.md"
license = "MIT"

[dependencies]
eui48 = "0.3.0"
rand = "0.4"
serde_json = "1.0.9"
mdns = { git = "https://github.com/plietar/rust-mdns" }
