[package]
name = "hap"
version = "0.0.1"
authors = ["Elias Wilken <elias@korhal.io>"]
description = "Rust implementation of the Apple HomeKit Accessory Protocol (HAP)"
homepage = "https://github.com/korhalio/hap-rs"
repository = "https://github.com/korhalio/hap-rs"
readme = "README.md"
license = "GPL-3.0"

[dependencies]
eui48 = "0.3.0"
rand = "0.4"
uuid = { version = "0.5.1", features = ["v4", "serde"] }
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
bytes = "0.4.6"
byteorder = "1.2.1"
rust-crypto = "0.2.36"
futures = "0.1.17"
hyper = "0.11.18"
route-recognizer = "0.1.12"
libmdns = "0.2.2"
srp = "0.2.4"
sha2 = "0.6.0"
pnet = "0.21.0"
num = "0.1.41"
ring = "0.13"
chacha20-poly1305-aead = "0.1.2"
tokio-core = "0.1.17"
tokio-io = "0.1.6"
erased-serde = "0.3.3"
url = "1.7.0"
failure = "0.1.1"
log = "0.4.4"

[build-dependencies]
uuid = { version = "0.5.1", features = ["v4", "serde"] }
handlebars = "0.32.1"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
