unstable_features = true
edition = "2018"
version = "Two"

comment_width = 120
fn_single_line = true
imports_layout = "HorizontalVertical"
max_width = 120
merge_imports = true
match_block_trailing_comma = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = true
match_arm_blocks = false
overflow_delimited_expr = true
